# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 450)
        Form.setMinimumSize(QtCore.QSize(500, 450))
        Form.setMaximumSize(QtCore.QSize(500, 450))
        Form.setStyleSheet("QWidget#Form{\n"
"    border-image: url(:/register/images/bj.png);\n"
"}")
        self.main_menue_btn = QtWidgets.QPushButton(Form)
        self.main_menue_btn.setGeometry(QtCore.QRect(10, 0, 41, 41))
        self.main_menue_btn.setStyleSheet("QPushButton{\n"
"    border-radius:15px;\n"
"    background-color:rgb(186, 186, 186);\n"
"    color: rgb(241, 241, 241);\n"
"    border: 1px solid;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(68, 68, 68);\n"
"}")
        self.main_menue_btn.setCheckable(True)
        self.main_menue_btn.setObjectName("main_menue_btn")
        self.exit_menue_btn = QtWidgets.QPushButton(Form)
        self.exit_menue_btn.setGeometry(QtCore.QRect(0, 90, 41, 41))
        self.exit_menue_btn.setStyleSheet("QPushButton{\n"
"    border-radius:15px;\n"
"    background-color:rgb(186, 186, 186);\n"
"    color: rgb(241, 241, 241);\n"
"    border: 1px solid;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(68, 68, 68);\n"
"}")
        self.exit_menue_btn.setCheckable(True)
        self.exit_menue_btn.setObjectName("exit_menue_btn")
        self.reset_menue_btn = QtWidgets.QPushButton(Form)
        self.reset_menue_btn.setGeometry(QtCore.QRect(60, 60, 41, 41))
        self.reset_menue_btn.setStyleSheet("QPushButton{\n"
"    border-radius:15px;\n"
"    background-color:rgb(186, 186, 186);\n"
"    color: rgb(241, 241, 241);\n"
"    border: 1px solid;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(68, 68, 68);\n"
"}")
        self.reset_menue_btn.setCheckable(True)
        self.reset_menue_btn.setObjectName("reset_menue_btn")
        self.about_menue_btn = QtWidgets.QPushButton(Form)
        self.about_menue_btn.setGeometry(QtCore.QRect(80, 0, 41, 41))
        self.about_menue_btn.setStyleSheet("QPushButton{\n"
"    border-radius:15px;\n"
"    background-color:rgb(186, 186, 186);\n"
"    color: rgb(241, 241, 241);\n"
"    border: 1px solid;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(68, 68, 68);\n"
"}")
        self.about_menue_btn.setCheckable(True)
        self.about_menue_btn.setObjectName("about_menue_btn")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(220, 250, 231, 328))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.account = QtWidgets.QLineEdit(self.layoutWidget)
        self.account.setStyleSheet("background-color: transparent;\n"
"color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-bottom:1px solid lightgray")
        self.account.setClearButtonEnabled(True)
        self.account.setObjectName("account")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.account)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("color: rgb(168, 168, 168);\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.password = QtWidgets.QLineEdit(self.layoutWidget)
        self.password.setStyleSheet("background-color: transparent;\n"
"color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-bottom:1px solid lightgray")
        self.password.setClearButtonEnabled(True)
        self.password.setObjectName("password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.password)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.confim_pwd = QtWidgets.QLineEdit(self.layoutWidget)
        self.confim_pwd.setStyleSheet("background-color: transparent;\n"
"color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-bottom:1px solid lightgray")
        self.confim_pwd.setClearButtonEnabled(True)
        self.confim_pwd.setObjectName("confim_pwd")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.confim_pwd)
        self.register_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.register_btn.setEnabled(False)
        self.register_btn.setMinimumSize(QtCore.QSize(0, 35))
        self.register_btn.setStyleSheet("QPushButton{\n"
"    border-radius:10px;\n"
"    background-color: rgb(27, 27, 27);\n"
"    color: rgb(241, 241, 241);\n"
"    border: 1px solid;\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    background-color: rgb(177, 177, 177);\n"
"    border-radius:10px;\n"
"    color: rgb(241, 241, 241);\n"
"    border: 1px solid;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.register_btn.setObjectName("register_btn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.register_btn)
        self.exit_menue_btn.raise_()
        self.reset_menue_btn.raise_()
        self.about_menue_btn.raise_()
        self.layoutWidget.raise_()
        self.main_menue_btn.raise_()

        self.retranslateUi(Form)
        self.main_menue_btn.clicked['bool'].connect(Form.show_hide_menue) # type: ignore
        self.about_menue_btn.clicked.connect(Form.about) # type: ignore
        self.reset_menue_btn.clicked.connect(Form.reset) # type: ignore
        self.exit_menue_btn.clicked.connect(Form.exit_pane) # type: ignore
        self.register_btn.clicked.connect(Form.check_register) # type: ignore
        self.account.textChanged['QString'].connect(Form.enable_gister_btn) # type: ignore
        self.password.textChanged['QString'].connect(Form.enable_gister_btn) # type: ignore
        self.confim_pwd.textChanged['QString'].connect(Form.enable_gister_btn) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.main_menue_btn.setText(_translate("Form", "菜单"))
        self.exit_menue_btn.setText(_translate("Form", "退出"))
        self.reset_menue_btn.setText(_translate("Form", "重置"))
        self.about_menue_btn.setText(_translate("Form", "关于"))
        self.label.setText(_translate("Form", "账   号"))
        self.label_2.setText(_translate("Form", "密   码"))
        self.label_3.setText(_translate("Form", "确认密码"))
        self.register_btn.setText(_translate("Form", "注册"))
import images_rc
